sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake
script:
  - mkdir -p build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=$(pwd)/../cmake/toolchain-travis-ci.cmake .. && make && make test
